### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by no-reply** [curationexperts/mahonia#7]
Are we using Apache 2?

  - [x] Choose a License and ensure legal details about contributions. - see #64
  - [x] Get CLAs from OHSU if appropriate. - see #8
  - [x] Add License file to repository - see #64
  - [x] Add License info to README.md - N/A
